package UI;

import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import Data.*;

public class UISwing extends JFrame implements UI {

    private ResourceBundle bundle = java.util.ResourceBundle.getBundle("oop/tictactoe/Bundle");
    private int selectedSquare = -1;
    private int selectedMenuOption = -1;
    private JButton[][] boardUI;
    private String defaultInforMEssage = bundle.getString("MessageWelcome");

    /** Creates new form UISwing */
    public UISwing() {
        try {

            // Se inician los componentes Swign (Código auto generado por NetBeans
            initComponents();

            // Se usa el look and Feel del sistema operativo
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
            
            SwingUtilities.updateComponentTreeUI(this);

            // Se cambia el ícono de la aplicación
            this.setIconImage(new ImageIcon(
                    getClass().getResource("/oop/tictactoe/resources/new.png")).getImage());

            // Se empaquetan los componentes y se hace visible el frame principal
            this.pack();
            this.setVisible(true);

            // Se crea una matriz de botones para trabajar con el tablero facilmente
            boardUI = new JButton[][]{
                {bSquare1, bSquare2, bSquare3},
                {bSquare4, bSquare5, bSquare6},
                {bSquare7, bSquare8, bSquare9}};

            // ...
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UISwing.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(UISwing.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(UISwing.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(UISwing.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    // UIManager.setLookAndFeel("org.pushingpixels.substance.api.skin.SubstanceAutumnLookAndFeel");
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        pBoard = new javax.swing.JPanel();
        bSquare1 = new javax.swing.JButton();
        bSquare2 = new javax.swing.JButton();
        bSquare3 = new javax.swing.JButton();
        bSquare4 = new javax.swing.JButton();
        bSquare5 = new javax.swing.JButton();
        bSquare6 = new javax.swing.JButton();
        bSquare7 = new javax.swing.JButton();
        bSquare8 = new javax.swing.JButton();
        bSquare9 = new javax.swing.JButton();
        pMainMenu = new javax.swing.JPanel();
        bOptionNewGame = new javax.swing.JButton();
        bOptionExit = new javax.swing.JButton();
        lInfoMessage = new javax.swing.JLabel();
        mMenu = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        mNewGame = new javax.swing.JMenuItem();
        mExit = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        mAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("oop/tictactoe/Bundle"); // NOI18N
        setTitle(bundle.getString("UISwing.title")); // NOI18N
        setName("mainFrame"); // NOI18N
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        bSquare1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        bSquare1.setEnabled(false);
        bSquare1.setMaximumSize(new java.awt.Dimension(50, 50));
        bSquare1.setMinimumSize(new java.awt.Dimension(50, 50));
        bSquare1.setPreferredSize(new java.awt.Dimension(50, 50));
        bSquare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSquare1ActionPerformed(evt);
            }
        });

        bSquare2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        bSquare2.setEnabled(false);
        bSquare2.setMaximumSize(new java.awt.Dimension(50, 50));
        bSquare2.setMinimumSize(new java.awt.Dimension(50, 50));
        bSquare2.setPreferredSize(new java.awt.Dimension(50, 50));
        bSquare2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSquare2ActionPerformed(evt);
            }
        });

        bSquare3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        bSquare3.setEnabled(false);
        bSquare3.setIconTextGap(-50);
        bSquare3.setMaximumSize(new java.awt.Dimension(50, 50));
        bSquare3.setMinimumSize(new java.awt.Dimension(50, 50));
        bSquare3.setPreferredSize(new java.awt.Dimension(50, 50));
        bSquare3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSquare3ActionPerformed(evt);
            }
        });

        bSquare4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        bSquare4.setEnabled(false);
        bSquare4.setMaximumSize(new java.awt.Dimension(50, 50));
        bSquare4.setMinimumSize(new java.awt.Dimension(50, 50));
        bSquare4.setPreferredSize(new java.awt.Dimension(50, 50));
        bSquare4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSquare4ActionPerformed(evt);
            }
        });

        bSquare5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        bSquare5.setEnabled(false);
        bSquare5.setMaximumSize(new java.awt.Dimension(50, 50));
        bSquare5.setMinimumSize(new java.awt.Dimension(50, 50));
        bSquare5.setPreferredSize(new java.awt.Dimension(50, 50));
        bSquare5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSquare5ActionPerformed(evt);
            }
        });

        bSquare6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        bSquare6.setEnabled(false);
        bSquare6.setMaximumSize(new java.awt.Dimension(50, 50));
        bSquare6.setMinimumSize(new java.awt.Dimension(50, 50));
        bSquare6.setPreferredSize(new java.awt.Dimension(50, 50));
        bSquare6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSquare6ActionPerformed(evt);
            }
        });

        bSquare7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        bSquare7.setEnabled(false);
        bSquare7.setMaximumSize(new java.awt.Dimension(50, 50));
        bSquare7.setMinimumSize(new java.awt.Dimension(50, 50));
        bSquare7.setPreferredSize(new java.awt.Dimension(50, 50));
        bSquare7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSquare7ActionPerformed(evt);
            }
        });

        bSquare8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        bSquare8.setEnabled(false);
        bSquare8.setMaximumSize(new java.awt.Dimension(50, 50));
        bSquare8.setMinimumSize(new java.awt.Dimension(50, 50));
        bSquare8.setPreferredSize(new java.awt.Dimension(50, 50));
        bSquare8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSquare8ActionPerformed(evt);
            }
        });

        bSquare9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        bSquare9.setEnabled(false);
        bSquare9.setMaximumSize(new java.awt.Dimension(50, 50));
        bSquare9.setMinimumSize(new java.awt.Dimension(50, 50));
        bSquare9.setPreferredSize(new java.awt.Dimension(50, 50));
        bSquare9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSquare9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBoardLayout = new javax.swing.GroupLayout(pBoard);
        pBoard.setLayout(pBoardLayout);
        pBoardLayout.setHorizontalGroup(
            pBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pBoardLayout.createSequentialGroup()
                        .addComponent(bSquare1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSquare2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pBoardLayout.createSequentialGroup()
                        .addComponent(bSquare7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSquare8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pBoardLayout.createSequentialGroup()
                        .addComponent(bSquare4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSquare5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSquare6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSquare9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSquare3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pBoardLayout.setVerticalGroup(
            pBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pBoardLayout.createSequentialGroup()
                        .addComponent(bSquare6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSquare9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pBoardLayout.createSequentialGroup()
                        .addGroup(pBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSquare3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSquare2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSquare1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSquare5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSquare4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSquare7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSquare8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bOptionNewGame.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        bOptionNewGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/tictactoe/resources/new.png"))); // NOI18N
        bOptionNewGame.setMnemonic(java.util.ResourceBundle.getBundle("oop/tictactoe/Bundle").getString("OptionNewGame").charAt(0));
        bOptionNewGame.setText(bundle.getString("OptionNewGame")); // NOI18N
        bOptionNewGame.setToolTipText(bundle.getString("OptionNewGame")); // NOI18N
        bOptionNewGame.setFocusable(false);
        bOptionNewGame.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bOptionNewGame.setIconTextGap(8);
        bOptionNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOptionNewGameActionPerformed(evt);
            }
        });

        bOptionExit.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        bOptionExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/tictactoe/resources/logout.png"))); // NOI18N
        bOptionExit.setMnemonic(java.util.ResourceBundle.getBundle("oop/tictactoe/Bundle").getString("OptionExit").charAt(0));
        bOptionExit.setText(bundle.getString("OptionExit")); // NOI18N
        bOptionExit.setToolTipText(bundle.getString("OptionExit")); // NOI18N
        bOptionExit.setFocusable(false);
        bOptionExit.setHideActionText(true);
        bOptionExit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bOptionExit.setIconTextGap(8);
        bOptionExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOptionExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMainMenuLayout = new javax.swing.GroupLayout(pMainMenu);
        pMainMenu.setLayout(pMainMenuLayout);
        pMainMenuLayout.setHorizontalGroup(
            pMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bOptionNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bOptionExit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pMainMenuLayout.setVerticalGroup(
            pMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bOptionExit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bOptionNewGame))
                .addContainerGap())
        );

        pMainMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bOptionExit, bOptionNewGame});

        lInfoMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lInfoMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lInfoMessage.setText(bundle.getString("MessageWelcome")); // NOI18N

        mMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mMenu.setPreferredSize(new java.awt.Dimension(60, 41));

        mFile.setMnemonic('F');
        mFile.setText(bundle.getString("MenuFile")); // NOI18N
        mFile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mFile.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        mFile.setIconTextGap(15);

        mNewGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mNewGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/tictactoe/resources/new.png"))); // NOI18N
        mNewGame.setMnemonic(java.util.ResourceBundle.getBundle("oop/tictactoe/Bundle").getString("OptionNewGame").charAt(0));
        mNewGame.setText(bundle.getString("OptionNewGame")); // NOI18N
        mNewGame.setToolTipText(bundle.getString("OptionNewGame")); // NOI18N
        mNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNewGameActionPerformed(evt);
            }
        });
        mFile.add(mNewGame);

        mExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/tictactoe/resources/logout.png"))); // NOI18N
        mExit.setMnemonic(java.util.ResourceBundle.getBundle("oop/tictactoe/Bundle").getString("OptionExit").charAt(0));
        mExit.setText(bundle.getString("OptionExit")); // NOI18N
        mExit.setToolTipText(bundle.getString("OptionExit")); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, bOptionExit, org.jdesktop.beansbinding.ELProperty.create("${action.enabled}"), mExit, org.jdesktop.beansbinding.BeanProperty.create("action"));
        bindingGroup.addBinding(binding);

        mExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExitActionPerformed(evt);
            }
        });
        mFile.add(mExit);

        mMenu.add(mFile);

        mHelp.setMnemonic('H');
        mHelp.setText(bundle.getString("MenuHelp")); // NOI18N
        mHelp.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        mHelp.setIconTextGap(15);

        mAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oop/tictactoe/resources/about.png"))); // NOI18N
        mAbout.setMnemonic('A');
        mAbout.setText(bundle.getString("MenuAbout")); // NOI18N
        mHelp.add(mAbout);

        mMenu.add(mHelp);

        setJMenuBar(mMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(pMainMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pBoard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lInfoMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lInfoMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOptionNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOptionNewGameActionPerformed

        selectedSquare = -1;
        selectedMenuOption = 1;

        changeBoardState(true);

    }//GEN-LAST:event_bOptionNewGameActionPerformed

    private void bOptionExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOptionExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bOptionExitActionPerformed

    private void bSquare1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSquare1ActionPerformed
        selectButton(1);
    }//GEN-LAST:event_bSquare1ActionPerformed

    private void bSquare2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSquare2ActionPerformed
        selectButton(2);
    }//GEN-LAST:event_bSquare2ActionPerformed

    private void bSquare3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSquare3ActionPerformed
        selectButton(3);
    }//GEN-LAST:event_bSquare3ActionPerformed

    private void bSquare4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSquare4ActionPerformed
        selectButton(4);
    }//GEN-LAST:event_bSquare4ActionPerformed

    private void bSquare5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSquare5ActionPerformed
        selectButton(5);
    }//GEN-LAST:event_bSquare5ActionPerformed

    private void bSquare6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSquare6ActionPerformed
        selectButton(6);
    }//GEN-LAST:event_bSquare6ActionPerformed

    private void bSquare7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSquare7ActionPerformed
        selectButton(7);
    }//GEN-LAST:event_bSquare7ActionPerformed

    private void bSquare8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSquare8ActionPerformed
        selectButton(8);
    }//GEN-LAST:event_bSquare8ActionPerformed

    private void bSquare9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSquare9ActionPerformed
        selectButton(9);
    }//GEN-LAST:event_bSquare9ActionPerformed

    private void mExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExitActionPerformed
        bOptionExitActionPerformed(evt);
    }//GEN-LAST:event_mExitActionPerformed

    private void mNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNewGameActionPerformed
        bOptionNewGameActionPerformed(evt);
    }//GEN-LAST:event_mNewGameActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        char keyPressed = evt.getKeyChar();
        
        if (keyPressed >= 48 && keyPressed <= 57) {
            selectedSquare = (int) keyPressed - 48;
        }

    }//GEN-LAST:event_formKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOptionExit;
    private javax.swing.JButton bOptionNewGame;
    private javax.swing.JButton bSquare1;
    private javax.swing.JButton bSquare2;
    private javax.swing.JButton bSquare3;
    private javax.swing.JButton bSquare4;
    private javax.swing.JButton bSquare5;
    private javax.swing.JButton bSquare6;
    private javax.swing.JButton bSquare7;
    private javax.swing.JButton bSquare8;
    private javax.swing.JButton bSquare9;
    private javax.swing.JLabel lInfoMessage;
    private javax.swing.JMenuItem mAbout;
    private javax.swing.JMenuItem mExit;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenuBar mMenu;
    private javax.swing.JMenuItem mNewGame;
    private javax.swing.JPanel pBoard;
    private javax.swing.JPanel pMainMenu;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public void printWelcome(Player player1, Player player2) {
    }

    @Override
    public int askMovement(Board board, char player) {

        printBoard(board);

        String infoMessage = bundle.getString("MessageYourTurn");
        lInfoMessage.setText(infoMessage);

        int lastSelectedSquare = selectedSquare;
        while (lastSelectedSquare == selectedSquare) {
            pause();
        }

        return selectedSquare;
    }

    @Override
    public void printError(String error) {
        lInfoMessage.setText(error);
    }

    @Override
    public void printBoard(Board board) {

        Square[][] squares = board.getBoard();
        for (int row = 0; row < squares.length; row++) {
            for (int col = 0; col < squares[row].length; col++) {
                boardUI[row][col].setText(squares[row][col].toString());
            }
        }
    }

    @Override
    public void printWinner(Player player) {

        lInfoMessage.setText(defaultInforMEssage);

        changeBoardState(false);

        if (player.isHumanPlayer()) {
            JOptionPane.showMessageDialog(
                    this,
                    bundle.getString("MessageVictory"),
                    bundle.getString("MessageGameOver"),
                    JOptionPane.INFORMATION_MESSAGE,
                    new ImageIcon(getClass().getResource("/oop/tictactoe/resources/happy.png")));
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    bundle.getString("MessageLose"),
                    bundle.getString("MessageGameOver"),
                    JOptionPane.INFORMATION_MESSAGE,
                    new ImageIcon(getClass().getResource("/oop/tictactoe/resources/sad.png")));
        }
    }

    @Override
    public void printTie() {

        JOptionPane.showMessageDialog(
                this,
                bundle.getString("MessageTie"),
                bundle.getString("MessageGameOver"),
                JOptionPane.INFORMATION_MESSAGE,
                new ImageIcon(getClass().getResource("/oop/tictactoe/resources/plain.png")));

        lInfoMessage.setText(defaultInforMEssage);
    }

    @Override
    public void printMenu() {
        selectedMenuOption = -1;
    }

    @Override
    public int askMenuOption() {
        while (selectedMenuOption == -1) {
            pause();
        }
        return selectedMenuOption;
    }

    private void pause() {
        try {
            Thread.sleep(50);
        } catch (InterruptedException ex) {
            Logger.getLogger(UISwing.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void changeBoardState(boolean state) {

        for (int row = 0; row < boardUI.length; row++) {

            for (int col = 0; col < boardUI[row].length; col++) {
                boardUI[row][col].setEnabled(state);
            }
        }
    }

    public void selectButton(int square) {
        selectedSquare = square;
    }
}
